language: node_js
node_js:
  - "10"
script:
  - npm install
  - npm run test
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - git reset --hard
    - node scripts/triggerTravisBuild.js
  on:
    branch: master
