language: node_js
node_js:
  - "10"
script:
  - npm ci
  - npm run test
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - node $TRAVIS_BUILD_DIR/scripts/triggerTravisBuild.js
  on:
    branch: master
